[package]
name = "raspberry-pi-car-development-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
wiringpi = "0.2.4"
